### ISSUE TITLE
Support POST?

### ISSUE THREAD

**Issue by mifi** [kodie/redirectmeto#1]
Thanks for sharing this great little tool. I'm trying to use it with Sign in with Apple, but they use POST on their OAuth callback URL. Not sure if it's feasable to support forwarding the request body as well, in case of POST/PUT etc.

In case of apple sign in:

Content type: `application/x-www-form-urlencoded`

form data:

```
state: 123
code: 456
```

Edit: I realised there is a http status code 307 that apparently does this https://softwareengineering.stackexchange.com/a/99966

**Comment by mifi** [comment]
I just deployed a cloudflare worker with this code and it works with Apple / POST `application/x-www-form-urlencoded`!
```js
export default {
  async fetch(request, env, ctx) {
    var url = new URL(request.url)
    var redirectUrl = url.pathname.substring(1) + url.search
    return Response.redirect(redirectUrl, 307)
  }
}
```

**Comment by kodie** [comment]
@mifi I just updated the the CloudFlare worker and the readme. Thanks for the contribution!
